### ISSUE TITLE
TDDのプロセスを開始する(BeerListContainer)

### ISSUE THREAD

**Issue by murnana** [murnana/react-tdd-sample#2]

**Comment by murnana** [comment]
写経後レッド & WARNING。
```PowerShell
> Executing task: mocha --require setup.js *.spec.js <

DECPRECATION WARNING: the xmlchar *module* is deprecated: please replace e.g. require('xmlchars') with require('xmlchars/xml/...')


  BeerListContainer
    1) should render InputArea and BeerList


  0 passing (41ms)
  1 failing

  1) BeerListContainer
       should render InputArea and BeerList:
     Error:
      Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none.
      To configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`      before using any of Enzyme's top level APIs, where `Adapter` is the adapter
      corresponding to the library currently being tested. For example:

      import Adapter from 'enzyme-adapter-react-15';

      To find out more about this, see http://airbnb.io/enzyme/docs/installation/index.html

      at validateAdapter (node_modules\enzyme\build\validateAdapter.js:16:11)
      at getAdapter (node_modules\enzyme\build\getAdapter.js:27:36)
      at new ShallowWrapper (node_modules\enzyme\build\ShallowWrapper.js:183:47)
      at shallow (node_modules\enzyme\build\shallow.js:21:10)
      at Context.<anonymous> (path/to/react-tdd-sample/components.spec.js:8:25)
```

**Comment by murnana** [comment]
修正 https://github.com/murnana/react-tdd-sample/commit/9822240c369f8617c8592a448c902642a18457cc

あとは
> 確かめる場合には、divを他のdivでラップしても、テストに通るか試してみてください。

をやってみる

**Comment by murnana** [comment]
```javascript
export class BeerListContainer extends Component {
    render() {
        return (
            <div>
                <div>
                    <InputArea />
                    <BeerList />
                </div>
            </div>
        );
    }
};
```
普通に通ってしまった。
https://github.com/airbnb/enzyme/blob/master/docs/api/ShallowWrapper/containsAllMatchingElements.md を見る限り、`containsAllMatchingElements`は厳密にツリーをチェックしてくれているわけではなく、指定された要素が期待通りの要素を持っているか程度のチェックしかしてくれないらしい。なので、InputAreaとBeerListを逆にしても通るし、余計なものを持っていても通る。また、1要素を`<div>`で囲っても通る。

```javascript
export class BeerListContainer extends Component {
    render() {
        return (
            <div>
                <input />
                <ul />
            </div>
        );
    }
};
```
これはRedになる。
